project_name: gohello
env:
  - GO111MODULE=on
before:
  hooks:
    - go mod tidy
builds:
  - main: .
    binary: gohello
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
      - 386
    ignore:
      - goos: darwin
        goarch: 386
    ldflags:
      - -s -w
      - -X main.Version={{.Version}}
      - -X main.Revision={{.ShortCommit}}
    env:
      - CGO_ENABLED=0
archives:
  - name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    replacements:
      darwin: darwin
      linux: linux
      windows: windows
      386: i386
      amd64: x86_64
    format_overrides:
      - goos: windows
        format: zip
release:
  prerelease: auto

# see: [Customization · GoReleaser](https://goreleaser.com/customization/#NFPM)
# copy from https://github.com/cohenjo/replicator/blob/master/.goreleaser.yml
# and https://github.com/runeimp/templar/blob/master/.goreleaser.yml
nfpms:
  - formats:
      - deb
      - rpm
    id: gohello
    replacements:
      386: i386
      amd64: x86_64
      darwin: macos
    bindir: /usr/local/bin/
    homepage: https://github.com/heiwa4126/gohello
    description: A example code for GitHub Actions and goreleaser
    maintainer: heiwa4126 <heiwa4126@gmail.com>
    vendor: Me
    license: MIT
