project_name: gohello
env:
  - GO111MODULE=on
before:
  hooks:
    - go mod tidy
builds:
  - main: .
    binary: gohello
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
      - 386
    ignore:
      - goos: darwin
        goarch: 386
    ldflags:
      - -s -w
      - -X main.Version={{.Version}}
      - -X main.Revision={{.ShortCommit}}
    env:
      - CGO_ENABLED=0
archives:
  - name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    replacements:
      darwin: darwin
      linux: linux
      windows: windows
      386: i386
      amd64: x86_64
    format_overrides:
      - goos: windows
        format: zip
release:
  prerelease: auto

# copy from https://github.com/cohenjo/replicator/blob/master/.goreleaser.yml
nfpm:
  name_template: '{{ .ProjectName }}_{{ .Arch }}'
  homepage:  https://github.com/heiwa4126/gohello
  description: A example code for GitHub Actions + goreleaser
  maintainer: heiwa4126 <heiwa4126@gmail.com>
  license: MIT
  vendor: Me
  formats:
    - deb
    - rpm
  recommends:
    - rpm
  bindir:  /usr/local/bin/

  # empty_folders:
  #   - /var/log/gohello
  # files:
  #   "init/gohello.service": "/usr/lib/systemd/system/gohello.service"
  #   "resources/**/*": "/usr/local/gohello/resources/"
  # config_files:
  #   "conf/gohello.conf.sample": "/etc/gohello.conf"
